import {useState} from 'react';
import {Link,Navigate,useNavigate} from 'react-router-dom';
import {Zap,ArrowRight,ShieldCheck,Dumbbell} from 'lucide-react';
import {useAuth,homeFor} from '../context/AuthContext';
import {useHealth} from '../hooks/useResource';
import {ErrorBox} from '../components/common/UI';
export function LoginPage(){const {user,login,loading,validationError}=useAuth(),navigate=useNavigate(),health=useHealth();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');if(!loading&&user)return <Navigate to={homeFor(user.role)} replace/>;async function submit(e){e.preventDefault();setBusy(true);setError('');try{const u=await login(email,password);navigate(homeFor(u.role))}catch(e){setError(e.message)}finally{setBusy(false)}}async function demo(mail){setEmail(mail);setPassword('Password123');setBusy(true);setError('');try{const u=await login(mail,'Password123');navigate(homeFor(u.role))}catch(e){setError(e.message)}finally{setBusy(false)}}return <AuthShell><div className={`api-status ${health?.status==='ONLINE'?'online':'offline-text'}`}><i/> API: {health?.status||'CONECTANDO'} (3000)</div><div className="eyebrow">BIENVENIDO A TU SIGUIENTE NIVEL</div><h1>El control.<br/>En tus manos<span className="title-dot">.</span></h1><p className="auth-subtitle">Inicia sesión y mantén tu gimnasio en movimiento.</p>{health?.demo&&<div className="demo-credentials"><span>ACCESO DE DEMOSTRACIÓN · 1 CLIC</span><div>{[['Administrador','admin@correo.com'],['Recepción','recepcion@correo.com'],['Socio','socio@correo.com']].map(([label,mail])=><button key={mail} className="secondary" disabled={busy} onClick={()=>demo(mail)}>{label}</button>)}</div></div>}<form onSubmit={submit}><label>Correo electrónico<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{(error||validationError)&&<ErrorBox message={error||validationError}/>}<button className="primary" disabled={busy||loading}>{busy?'Iniciando sesión…':'Iniciar sesión'}<ArrowRight/></button></form><p className="auth-switch">¿Primera vez aquí? <Link to="/registro">Crear cuenta de socio</Link></p><div className="auth-security"><ShieldCheck size={15}/> Sesión protegida con JWT y permisos por rol</div></AuthShell>}
export function RegisterPage(){const {register,user}=useAuth(),navigate=useNavigate();const [error,setError]=useState(''),[busy,setBusy]=useState(false);if(user)return <Navigate to={homeFor(user.role)} replace/>;async function submit(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));setBusy(true);setError('');try{await register(body);navigate('/mi-perfil')}catch(e){setError(e.message)}finally{setBusy(false)}}return <AuthShell><div className="eyebrow">TU NUEVA RUTINA EMPIEZA AQUÍ</div><h1>Únete a PULSE<span className="title-dot">.</span></h1><p className="auth-subtitle">Crea tu cuenta y consulta tu membresía, pagos y visitas.</p><form onSubmit={submit}><label>Nombre completo<input name="name" required maxLength={80} autoComplete="name"/></label><label>Cédula<input name="dni" required pattern="[0-9]{6,12}" inputMode="numeric" title="Entre 6 y 12 dígitos"/></label><label>Correo electrónico<input type="email" name="email" autoComplete="username" required maxLength={120}/></label><label>Contraseña<input type="password" name="password" minLength={8} maxLength={72} autoComplete="new-password" required/></label><p className="card-subtitle">Tu cuenta se crea como Socio. Recepción activará la membresía cuando registres el pago. Las cuentas de personal las crea el administrador.</p>{error&&<ErrorBox message={error}/>}<button className="primary" disabled={busy}>{busy?'Creando cuenta…':'Crear cuenta'}<ArrowRight/></button></form><p className="auth-switch">¿Ya tienes cuenta? <Link to="/login">Iniciar sesión</Link></p></AuthShell>}
function AuthShell({children}){return <div className="auth-page"><section className="auth-art"><Link className="brand" to="/login"><span className="brand-icon"><Zap fill="currentColor"/></span>PULSE<span className="brand-dot">.</span></Link><div className="auth-art-main"><div className="sport-mark"><Dumbbell/></div><div className="eyebrow">BUILT FOR MOVEMENT</div><h2>STRONGER<br/>EVERY<br/><span>DAY.</span></h2><p>Más que un gimnasio.<br/>Una comunidad en movimiento.</p></div><span className="auth-art-footer">GYM OPERATIONS & MEMBERSHIP SUITE</span></section><section className="auth-form-panel"><div className="auth-form">{children}</div></section></div>}
