import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Users,DollarSign,Clock,Plus} from 'lucide-react';
import {useResource,useHealth} from '../hooks/useResource';
import {currency} from '../services/api';
import {PageHeading} from '../components/layout/Layout';
import {Loading,ErrorBox} from '../components/common/UI';
import AttendanceChart from '../components/dashboard/AttendanceChart';
import CheckInPanel from '../components/checkin/CheckInPanel';
import MemberTable,{MemberEditor} from '../components/members/MemberTable';
export function Kpis({data}) {return <div className="kpis"><article className="card kpi"><div className="kpi-top">Socios Activos<span className="kpi-icon"><Users/></span></div><div className="kpi-number">{data.activeMembers.toString().padStart(2,'0')}</div><div className="kpi-bottom">Membresías habilitadas y vigentes</div></article><article className="card kpi"><div className="kpi-top">Ingresos del Día<span className="kpi-icon"><DollarSign/></span></div><div className="kpi-number financial-number">{currency(data.dailyRevenue)}</div><div className="kpi-bottom">Pagos registrados hoy · COP</div></article><article className="card kpi"><div className="kpi-top">Membresías por Vencer<span className="kpi-icon"><Clock/></span></div><div className="kpi-number">{data.expiringMemberships.toString().padStart(2,'0')}</div><div className="kpi-bottom"><span className="trend orange">Próximos 7 días</span><Link className="text-button" to="/socios?estado=expiring">Ver socios →</Link></div></article></div>}
export default function DashboardPage(){const dash=useResource('/dashboard'),members=useResource('/members'),plans=useResource('/plans'),health=useHealth(),[editor,setEditor]=useState(false);const reload=()=>{dash.reload();members.reload()};return <><PageHeading title="Dashboard" subtitle="Todo lo que necesitas para mantener el ritmo."><button className="primary" onClick={()=>setEditor(true)} disabled={!plans.data}><Plus/> Nuevo socio</button></PageHeading>{dash.error&&<ErrorBox message={dash.error} retry={dash.reload}/>} {dash.loading&&!dash.data?<Loading/>:dash.data&&<><Kpis data={dash.data}/><div className="middle"><AttendanceChart bars={dash.data.attendance}/><CheckInPanel onEntry={dash.reload}/></div></>}{members.error&&<ErrorBox message={members.error} retry={members.reload}/>} {members.data&&plans.data&&<MemberTable members={members.data} plans={plans.data} compact onRefresh={reload} today={health?.date}/>} {plans.error&&<ErrorBox message={plans.error} retry={plans.reload}/>} {editor&&plans.data&&<MemberEditor plans={plans.data} onSaved={reload} onClose={()=>setEditor(false)}/>}</>}
