import {useState} from 'react';
import {IdCard,Activity,CalendarDays} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
import {useResource} from '../hooks/useResource';
import {currency,formatDate,initials} from '../services/api';
import {PageHeading} from '../components/layout/Layout';
import {Badge,Loading,ErrorBox} from '../components/common/UI';
import {Receipt} from '../components/members/MemberTable';
function MembershipQR({member}) {return member?.dni&&<div className="card-qr"><QRCodeSVG value={member.dni} size={112} marginSize={2} title="Cédula del socio para check-in"/><span>Tarjeta digital · Identificación del socio<br/>El acceso siempre se valida en la API.</span></div>}
export default function ProfilePage(){const profile=useResource('/me/profile'),[receipt,setReceipt]=useState(null);const p=profile.data;return <><PageHeading title="Mi perfil" subtitle="Tu progreso empieza con cada visita."/>{profile.loading&&!p&&<Loading/>}{profile.error&&<ErrorBox message={profile.error} retry={profile.reload}/>} {p&&<><div className="profile-grid"><article className="card membership-card"><div className="eyebrow">PULSE MEMBER</div><div className="membership-top"><span className="avatar">{initials(p.member?.name||p.user.name)}</span><Badge status={p.member?.status||'Inactivo'}/></div><h2>{p.member?.name||p.user.name}</h2><p>{p.user.email}</p><div className="membership-dni"><IdCard/> {p.member?.dni}</div><div className="receipt-row"><span>Plan actual</span><b>{p.member?.planName||'Sin plan'}</b></div><div className="receipt-row"><span>Vencimiento</span><b>{formatDate(p.member?.expiry)}</b></div><p className="card-subtitle">Presenta tu cédula en recepción para registrar el ingreso.</p><MembershipQR member={p.member}/></article><article className="card report-stat"><Activity className="accent"/><h2>Tu actividad</h2><strong>{p.visits.length}</strong><p className="card-subtitle">Visitas mostradas (últimas 20)</p><div className="receipt-row"><span>Última visita</span><b>{formatDate(p.visits[0]?.enteredAt)}</b></div><p className="muted">{p.member?.status==='Activo'?'Tu membresía está activa. ¡Nos vemos en el gimnasio!':'Acércate a recepción para activar o renovar tu membresía.'}</p></article></div><article className="card table-card"><div className="table-header"><h2>Mis pagos</h2></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Plan</th><th>Método</th><th>Total</th><th>Comprobante</th></tr></thead><tbody>{p.payments.length?p.payments.map(pay=><tr key={pay.id}><td>{formatDate(pay.createdAt)}</td><td>{pay.planName}</td><td>{pay.method}</td><td>{currency(pay.amount)}</td><td><button className="text-button" onClick={()=>setReceipt(pay)}>Ver comprobante</button></td></tr>):<tr><td colSpan="5" className="empty">Todavía no tienes pagos registrados.</td></tr>}</tbody></table></div></article><article className="card visits-card"><h2><CalendarDays size={17}/> Mis últimas visitas</h2><div className="visit-list">{p.visits.length?p.visits.map(v=><span key={v.id} className="plan">{formatDate(v.enteredAt)} · {new Date(v.enteredAt).toLocaleTimeString('es-CO',{timeZone:'America/Bogota',hour:'2-digit',minute:'2-digit'})}</span>):<p className="muted">Tu próxima visita puede ser la primera.</p>}</div></article></>}{receipt&&<Receipt receipt={receipt} onClose={()=>setReceipt(null)}/>}</>}
